### ISSUE TITLE
トラブルシュートでWindowsのポートチェックのコマンドが間違っている

### ISSUE THREAD

**Issue by tani-takanori** [ws-4020/mobile-app-crib-notes#117]
https://ws-4020.github.io/mobile-app-crib-notes/react-native/troubleshooting/unable-to-load-script#%E3%83%97%E3%83%AD%E3%82%BB%E3%82%B9%E3%81%AE%E5%81%9C%E6%AD%A2

```
netstat -nao | find 8081
```
エラーになるので、下記が正しい

```
netstat -nao | find "8081"
```

**Comment by in-a-paddy** [comment]
#118 で修正されているのでクローズ
