### ISSUE TITLE
Todo アプリの実装/状態に応じたナビゲーションでのファイル名

### ISSUE THREAD

**Issue by asahi99** [ws-4020/mobile-app-crib-notes#225]
http://localhost:3000/mobile-app-crib-notes/react-native/learn/todo-app/auth
にて
> /src/navigation/RootStackNav.tsxのファイル名をUnauthedStack.tsxに変更し、次のように修正してください。

との記述があるが、他ファイル名との統一からUnauthedStack **Nav** .tsx のミスと思われます。

**Comment by asahi99** [comment]
同ページで
> /src/screens/todo/TodoBoard.tsxを修正してください。
の下部のコードブロックのタイトルが
> /src/screens/settings/UserSetting.tsx
になっています。正しくは /src/screens/todo/TodoBoard.tsx でしょうか？

**Comment by takei0w0** [comment]
#227 にて対応済
