### ISSUE TITLE
M1 MacでPodsのインストール中にエラーが発生

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#279]
M1 Macで環境構築中にエラーが発生。
CocoaPodsの依存性をインストール中にエラー。

次のURLを参考に対応して解決しました。
https://github.com/CocoaPods/CocoaPods/issues/10684#issuecomment-852723356

Issueという訳ではありませんが（M1 Macのサポート状況は不明なため）、参考までに

**Comment by in-a-paddy** [comment]
解消したと思っていましたが、以下に該当する場合は現在もエラーが発生することが分かりました。

* Appleシリコン搭載のMac
* Rubyのバージョンが2.6以下

開発環境構築のガイドに明記して対応します。(#967)
