### ISSUE TITLE
アプリの実行の説明について

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#280]
アプリの実行の説明で、`Bare Workflowのアプリでも実行できます。`とありますが、`Bare Workflow` の説明がどこかでされていますでしょうか。

**Comment by tani-takanori** [comment]
Bare Workflowのページにリンクしておく

**Comment by tani-takanori** [comment]
https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/getting-started/create-project/
にある

https://github.com/expo/expo/tree/master/templates/expo-template-bare-typescript
がなくなっている...
