### ISSUE TITLE
アプリ実行の仕組みの位置

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#281]
- アプリ実行の仕組みについて、アプリ実行コマンドの前に説明があると嬉しいと感じました
- アプリの実行コマンドは「Expo Go」「iPhoneシミュレータ」「Androidエミュレータ」という単位で分かれているが、アプリの実行の説明は「React Native」「React Native + Expo」と分かれていて、対比がしにくく初学者は混乱を招きそうに感じました

**Comment by tani-takanori** [comment]
Expo + React Native -> Expo Go
React Native -> Android, iOSに分ける
