### ISSUE TITLE
gitのコミット

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#282]
各説明ポイントでgitのコミットを挟むという案は今回は見送られたのでしょうか。
かなりボリュームの多いコンテンツなので、エラーで立ち行かなくなった時に、比較できるgitコミットがあると嬉しいだろうと感じます。

**Comment by tani-takanori** [comment]
各ページで変更内容を確認してもらいつつgit commitしてもらう
