### ISSUE TITLE
Stackナビゲーション

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#283]
どの段階で動作確認を挟むのかが分かりにくく感じました。
例えば、`Welcome画面にヘッダーが表示されて、ログインボタンからログイン画面に遷移できたら成功です。 ログイン画面からWelcome画面に戻れることも確認してください。` の箇所まで動作確認せずに一気通貫する流れでしょうか？

**Comment by tani-takanori** [comment]
分かりづらい？？

**Comment by kozake** [comment]
基本的な流れとして、説明→修正→動作確認（画面イメージ） という流れがあるかと思うのですが、このセクションでは `Welcome画面にヘッダーが表示されて、ログインボタンからログイン画面に遷移できたら成功です。 ログイン画面からWelcome画面に戻れることも確認してください。` の動作確認が出た後、`ログイン画面からToDo一覧画面への遷移を実装` をした後に再度動作確認という流れになっていました。
修正量が多かったので、実は途中で動作確認の文章があった？と思って見直ししたのを覚えています。

1セクション内では基本的に動作確認は最後の一回だけ、もしくは途中で動作確認を挟む場合は、その画面イメージも挟んであげると分かりやすいかな？という風に感じました。

ただ、とはいえ「Stackナビゲーション」「状態に応じたナビゲーション」「Tabナビゲーション」「Modalスクリーン」はいずれのセクションもボリュームが多く、「Welcome」の次から流れるこのセクションのボリュームと難易度に大変さを感じるかもとも感じました。
いい感じに分割できるのであれば、そうしたほうがいいかもです。

**Comment by tani-takanori** [comment]
Navigationはむずいんやぞってジャブいれてもいいんかな？
