### ISSUE TITLE
演習課題の「実装の注意点と不具合の確認」に違和感

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#285]
演習課題に追加された「実装の注意点と不具合の確認」に次の理由で違和感があります。
- `REST APIとの接続` に進んでいない状態でAPI呼び出しによる注意が出てきている
- 内容が `React` での実装における注意点のように感じる。`React Native` としての演習課題として適切かどうか
- この注意点が実際の業務におけるよくある落とし穴であれば、演習課題ではなくきちんと回答まで説明したほうがいいのでは

**Comment by tani-takanori** [comment]
> この注意点が実際の業務におけるよくある落とし穴であれば、演習課題ではなくきちんと回答まで説明したほうがいいのでは

ここでの「回答」は不具合が発生する原因についての回答なのか「あるべき実装」なのかを確認

**Comment by tani-takanori** [comment]
SPAのハンズオンで不具合おきないんか？

**Comment by tani-takanori** [comment]
演習課題からは削除して、Noteで利用しているノウハウと簡単に紹介する。
