### ISSUE TITLE
応用編に違和感

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#286]
応用編の「遷移先の画面にパラメータを渡す」について、TODOアプリの実装として使う場面はなかったですが、基本的なアプリ開発でよく使う機能ではないでしょうか。
「TODOアプリの実装では使わないですが」の但し書きをしたうえで、「React Navigationの基本」に含めてもいいように感じました。

**Comment by tani-takanori** [comment]
基本に入れるとすると...

- Overview
- Stack
- Modal
- Tab
- Route

みたいになるのかな？

**Comment by tani-takanori** [comment]
> 応用編の「遷移先の画面にパラメータを渡す」について、TODOアプリの実装として使う場面はなかったですが、基本的なアプリ開発でよく使う機能ではないでしょうか。

この指摘に対応するとなると「基本的なアプリ開発でよく使う機能」を入れておかないとあかんのかな？

**Comment by tani-takanori** [comment]
Routeを使う場面やシチュエーションが整理できないと「基本なのか？」がわからない。

「React Navigationの基本」に入れるなら、そもそも学習コンテンツから落としていいのでは？

Reduxが市民権を得ている中でRouteを使うのか？
