### ISSUE TITLE
APIクライアントの作成の`npm script`

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#287]
APIクライアントの作成の`npm script`で起動するコマンドが提示されていない。次のコマンド実行が必要かと思います。

```
npm run api:gen-client
```

**Comment by in-a-paddy** [comment]
書いてあるのでクローズします。
https://github.com/ws-4020/mobile-app-crib-notes/blame/master/docs/react-native/learn/todo-app/networking/generate-api-client.mdx#L44
