### ISSUE TITLE
REST APIの呼びだし

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#289]
`TodoService`の修正について、変更箇所を差分で示さないのであれば全量置き換えのほうが有難いです。

**Comment by tani-takanori** [comment]
https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/todo-app/networking/api-request

`修正してください。` の文言を変える +  `TodoServiceは以下のような実装になります。` を前置き換えにするように修正する
