### ISSUE TITLE
ユーザー操作への応答

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#290]
ユーザー操作への応答については、「処理の追い抜き」（完了、未完了の操作処理順がネットワーク遅延などで逆転）した場合に不整合が発生しそうです。
一般に提示する実装としてはあまり好ましくないように感じました。

**Comment by tani-takanori** [comment]
ネットワーク遅延で逆転するケースは排他を使わないと不整合は防げないのでは？

todo -> completed -> 1. accept -> 4.return
completed -> todo  -> 2.accept -> 3.return

どっちのトランザクションが勝ったのかわからん。
片方がエラーになった場合の処理をどうするか？はエラーハンドリング側かな

**Comment by tani-takanori** [comment]
> ネットワーク遅延で逆転するケースは排他を使わないと不整合は防げないのでは？
> 
> 1. `todo -> completed` -> 1. API start  -> 4.return
> 2. `completed -> todo`  -> 2.API start -> 3.return
> 
> どっちのトランザクションが勝ったのかわからん。
> 片方がエラーになった場合の処理をどうするか？はエラーハンドリング側かな

**Comment by tani-takanori** [comment]
更新中のToDoをloading中にするか？
