### ISSUE TITLE
💬 第三者レビュー ログ-方式

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#553]
#### アプリのログ出力

- アプリのログ管理の仕組み
  - 最後のほうで「モバイルアプリ」という言葉を使っていましたが、「アプリ」との使い分けが気になりました。使い分けがないなら資料中は統一した方がよさそうに思いました。

**Comment by kozake** [comment]
### 対応内容

- アプリで統一する

**Comment by creature-water-valley** [comment]
Discussionsに移動

https://github.com/ws-4020/mobile-app-crib-notes/discussions/569
