### ISSUE TITLE
💬 第三者レビュー 環境切り替え-開発ガイド

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#555]
#### ビルドバリアントごとのアプリ起動

- 「Firebaseの機能を利用する」ではiOSが左、Androidが右だったのに、こちらでは逆になっていたのが気になりました
- 縦の並び順が「Firebaseの機能を利用する」と違うのが少し気になりました

**Comment by kozake** [comment]
### 対応内容

- iOS、Android順に修正
- 「Firebaseの機能を利用する」の順番にあわせる

**Comment by creature-water-valley** [comment]
Discussionsに移動

https://github.com/ws-4020/mobile-app-crib-notes/discussions/571
