### ISSUE TITLE
💬 第三者レビュー メッセージ-ADR

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#556]
#### メッセージ管理の方針

- 決定
  - 「サーバから取得する方式を採用せず」とありますがそれは議論の対象外だったのでしょうか。コンテキストではサーバで管理する方式のメリットも書いていたので、気になりました。

**Comment by kozake** [comment]
### 対応内容

- 「コスト削減を目的として～」と一文理由をつけて修正

**Comment by creature-water-valley** [comment]
Discussionsに移動

https://github.com/ws-4020/mobile-app-crib-notes/discussions/572
