### ISSUE TITLE
💬 第三者レビュー メッセージ-ソースコード

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#557]
### ソースコード

- メッセージキーが見つからない場合はメッセージキーを返却していますが、処理続行できるようにしているのでエラーレベルが警告ではないのか少し気になりました

- プレースホルダーで例えば`{0}`を同じメッセージ中に複数定義された場合の挙動が気になりました。方式の「メッセージのロード」では触れられておらず、実装を見ると最初にHitしたものが置換されるように見えましたので、仕様としてどこかに記載なくてもいいのか少し気になりました。

**Comment by kozake** [comment]
### 対応内容

- Firebase Crashlytics でエラーを収集しているから対応しない
- 正規表現を用いた置換でコードを修正する

**Comment by in-a-paddy** [comment]
第三者レビュー結果って、Issueにする必要ない気がしました。（外の人が見てもナンノコッチャわからないのでは？と。）

**Comment by creature-water-valley** [comment]
Discussionsに移動

https://github.com/ws-4020/mobile-app-crib-notes/discussions/573
