### ISSUE TITLE
santoku-appのStatefullLogin画面でUnmount Componentの更新が警告される

### ISSUE THREAD

**Issue by tani-takanori** [ws-4020/mobile-app-crib-notes#56]
iOSシミュレーターで確認。

DrawerメニューでStatelessを表示後、Statefullなログイン画面を表示するとワーニングが表示される

**Comment by takei0w0** [comment]
該当箇所が見当たらないのですがissue作成当時から変更があったのでしょうか

**Comment by in-a-paddy** [comment]
サンプルアプリケーションは再構築するので、このIssueはクローズします。
