### ISSUE TITLE
環境変数を追加・変更した際に必要な手順が開発ガイドに明記されていない。

### ISSUE THREAD

**Issue by kozake** [ws-4020/mobile-app-crib-notes#595]
環境変数を追加・変更した場合ネイティブビルドが必要になるが、その手順が開発ガイドに明記されていない。
変更しても `gradlew clean` を叩かないとキャッシュが残って反映されないなどの事象も発生しており、書いておいたほうが良さそう。

**Comment by in-a-paddy** [comment]
環境変数？ってなったんですが、[プロダクトフレーバー](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/development/build-configuration/product-flavor-configurations)の設定ですかね？

**Comment by in-a-paddy** [comment]
タスク管理に移動
AB#13178
