### ISSUE TITLE
トピック名が日本語だと通知を受け取れない

### ISSUE THREAD

**Issue by shkozake** [ws-4020/mobile-app-crib-notes#81]
トピック名が日本語だと通知を受け取れない。
トピック名は英数字のみという注意書きかバリデーションのいずれかが欲しい。
また、トピックに無事登録できたか失敗したかの通知も欲しい。

**Comment by tani-takanori** [comment]
FCMがTopicに許容している文字
`Invalid topic name: ¥^-0987654 does not match the allowed format [a-zA-Z0-9-_.~%]{1,900}.]`

**Comment by tani-takanori** [comment]
対応しました
https://github.com/ws-4020/mobile-app-crib-notes/pull/63/commits/c4e006311e948c4e4b2f84c13cf682b55000ef44
