### ISSUE TITLE
🐛: プロジェクトの作成ページのリンク先不備

### ISSUE THREAD

**Issue by OshitaTatsuya** [ws-4020/mobile-app-crib-notes#87]
以下それぞれののリンク先が、誤っている為、リンク先の修正が必要。

・「アプリを実装してする前に〜」
<アプリの実装前に > Overview>
https://ws-4020.github.io/mobile-app-crib-notes/react-native/learn/basic-concepts

・「〜Expoとは〜」
リンク先、要確認

**Comment by tani-takanori** [comment]
対応済み
